### ISSUE TITLE
Theming Optimizations

### ISSUE THREAD

**Issue by khuynh92** [LottieFiles/dotlottie-web#188] opened 2024-05-06 18:26 UTC
## Overview
My team is switching over from using the svg renderer from [@dotlottie/react-player](https://github.com/dotlottie/player-component?tab=readme-ov-file) to this package, and we're running into some issues with theming using this package. Our use case requires the need for dynamic theming through `loadThemeData`.

Asset used for the examples: https://lottie.host/5edd3191-18f1-4dcb-b6b5-1c00ef8b2f5c/UQ5qeVivMe.lottie
Codepen: https://codepen.io/khuynh92/pen/RwOzKGZ?editors=0010

## Slot ID implementation
Issue: There is no easy way to add a `sid` to a JSON file. Users have to go into a JSON file, locate the correct property, and  manually add the `sid`. This can become tedious if this has to be done to multiple files.

Expected Behavior: In After Effects, assets can have class names and id's injected into the JSON file simply by renaming the layer in AE. For example renaming a layer to `#star-outline.lottie-icon-outline` in AE will inject a class name of `.lottie-icon-outline` and an id of `#star-outline` in the exported JSON file.

It would be nice to be able to apply theme updates using the existing class name or id, that way we don't have to manually add sid to the JSON file, or if there was a script provided that added the sid automatically based off of existing class names or ids in that are in the JSON file.

## Updating static/paused assets
Issue:  When an asset is paused (or has finished animating), theme updates via `loadThemeData` or `loadTheme` do not trigger a theme update. Only when the animation begins to play again will the theme update.

Expected Behavior: using the methods `loadThemeData` or `loadTheme` should update the theme, even when paused.

<img width="300" alt="Screenshot 2024-05-06 at 11 04 39 AM" src="https://github.com/LottieFiles/dotlottie-web/assets/35128180/fad033a9-7534-4685-96a3-60ca779c2e14">

## Memory access out of bounds error when reverting back to default theme
Issue: Using `loadThemeData`, I'm running into issues when trying to revert an asset's theme back to the original data that's within the JSON file. Changing the theme works properly, but when reverting the theme back using `loadThemeData("")` or `loadTheme("")`, the manipulated property changes to black and error messages are thrown.

Expected Behavior: Theme should revert back to original colors from the JSON file.

<img width="300" alt="Screenshot 2024-05-06 at 11 04 39 AM" src="https://github.com/LottieFiles/dotlottie-web/assets/35128180/3d003bcd-f9a1-4d39-a46c-e0483131cedb">

<img width="300" alt="Screenshot 2024-05-06 at 11 04 39 AM" src="https://github.com/LottieFiles/dotlottie-web/assets/35128180/3a3084b7-84d2-49d0-bf56-9b828a600ad5">

...

## Motivation

> What inspired this enhancement? What makes you think this should be included?
The need for dynamic theming and ease of theming implementation

...

## Labels

- [ ] Add the `Type: Enhancement` label to this issue.

**Comment by theashraf** [comment] 2024-05-07 06:38
Thanks @khuynh92 for reporting these issues. We will look into it and get back to you with an easier way to set the slot IDs

**Comment by theashraf** [comment] 2024-05-08 16:41
@khuynh92 

You're right, setting the "sid" on lottie json properties manually is not easy. We're currently working on abstracting the theme creation process in [Lottie Creator](https://creator.lottiefiles.com/), but until that happens, there is a workaround that allows you to assign slot IDs to animated color properties to match the parent shape's existing class name or ID. You can use [relottie](https://github.com/LottieFiles/relottie) to parse the Lottie JSON into a relottie AST and traverse the AST to locate the target shapes by their class name or ID, and then modify their animated color properties' slot ID to match their parent Shapes class name or ID. 

> It would be nice to be able to apply theme updates using the existing class name or id, that way we don't have to manually add sid to the JSON file, or if there was a script provided that added the sid automatically based off of existing class names or ids in that are in the JSON file.


I've noted down the other two issues and have been able to replicate them. I will update you as soon as I have a fix

**Comment by theashraf** [comment] 2024-05-21 20:33
@khuynh92 

This part of the issue is fixed in dotlottie-web@0.22.0 release.

> Memory access out of bounds error when reverting back to default theme
Issue: Using loadThemeData, I'm running into issues when trying to revert an asset's theme back to the original data that's within the JSON file. Changing the theme works properly, but when reverting the theme back using loadThemeData("") or loadTheme(""), the manipulated property changes to black and error messages are thrown.

Will update you once the other part of the issue is resolved, thanks

**Comment by khuynh92** [comment] 2024-05-22 20:09
> Will update you once the other part of the issue is resolved, thanks

Appreciate it! Thanks for the consistent status updates 🙂

**Comment by theashraf** [comment] 2024-05-31 07:18
@khuynh92 This issue is resolved in [@lottiefiles/dotlottie-web@0.23.1](https://github.com/LottieFiles/dotlottie-web/releases/tag/%40lottiefiles%2Fdotlottie-web%400.23.1)

**Closed** 2024-06-02 07:23 UTC
Labels: bug, thorvg, core

**Comment by khuynh92** [comment] 2024-06-05 16:26
Thank you @theashraf! Verified in my codepen demo that the changes do work.

As for SID implementation, I'll be using the workaround method for now, but do you have a link to where I can track the progress for easier SID implementation?

**Comment by theashraf** [comment] 2024-11-21 07:43
@khuynh92, you might find it interesting that we've introduced theming in Lottie Creator! Now, you can create themes to your animations and play them on dotLottie players.

Check out the details here: https://lottiefiles.com/blog/working-with-lottie-animations/how-to-add-themes-to-lottie-animations-in-lottie-creator
